branches:
  only:
    - dev-master
language: python
compiler:
  - gcc
python:
  - "2.6"
env:
  - NUPIC=$TRAVIS_BUILD_DIR

notifications:
  irc: "irc.freenode.net#nupic"
  webhooks:
    urls:
      - http://issues.numenta.org:3031/travis
    on_success: always
    on_failure: always
    on_start: true

before_install:
  - "source $NUPIC/env.sh"
install: "$NUPIC/build.sh"

# dummy tests for now
script: "pwd"

after_success:
  - "echo yay!"
